// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmdFcMmh6g_L2cElAXZDVMa8wFRk72sHQ',
    appId: '1:936992453273:web:4b69f907fcb52834647e08',
    messagingSenderId: '936992453273',
    projectId: 'flashchat-df35d',
    authDomain: 'flashchat-df35d.firebaseapp.com',
    storageBucket: 'flashchat-df35d.appspot.com',
    measurementId: 'G-CN9SGD6KT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjjCBzEy3MEmrquEc39p-mfhFcFegjIzA',
    appId: '1:936992453273:android:11bfaa62d588bcaa647e08',
    messagingSenderId: '936992453273',
    projectId: 'flashchat-df35d',
    storageBucket: 'flashchat-df35d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgzcrwYEyeeTTBXDz677ycqNUq3R8fUC4',
    appId: '1:936992453273:ios:908002fcae1e90a5647e08',
    messagingSenderId: '936992453273',
    projectId: 'flashchat-df35d',
    storageBucket: 'flashchat-df35d.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgzcrwYEyeeTTBXDz677ycqNUq3R8fUC4',
    appId: '1:936992453273:ios:908002fcae1e90a5647e08',
    messagingSenderId: '936992453273',
    projectId: 'flashchat-df35d',
    storageBucket: 'flashchat-df35d.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmdFcMmh6g_L2cElAXZDVMa8wFRk72sHQ',
    appId: '1:936992453273:web:63cc5c08b5d509cb647e08',
    messagingSenderId: '936992453273',
    projectId: 'flashchat-df35d',
    authDomain: 'flashchat-df35d.firebaseapp.com',
    storageBucket: 'flashchat-df35d.appspot.com',
    measurementId: 'G-QFQXWEHNTS',
  );
}
